stages:
  - test

# Include GitLab's built-in security templates
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml

# Global security policy
variables:
  SAST_FAIL_ON_SEVERITY: "Medium"
  DEPENDENCY_SCANNING_FAIL_ON_SEVERITY: "Medium"
  SECRET_DETECTION_FAIL_ON_SEVERITY: "Medium"

# Ensure security jobs actually fail the pipeline
sast:
  artifacts:
    reports:
      sast: gl-sast-report.json

enforce_sast_severity:
  stage: enforce
  image: alpine:latest
  needs:
    - job: sast
      artifacts: true
  script:
    - apk add --no-cache jq
    - |
      COUNT=$(jq '[.vulnerabilities[]
        | select(.severity == "Medium" or .severity == "High" or .severity == "Critical")
      ] | length' gl-sast-report.json)

      if [ "$COUNT" -gt 0 ]; then
        echo "❌ SAST found $COUNT Medium+ vulnerabilities"
        exit 1
      fi

      echo "✅ No Medium+ SAST vulnerabilities found"

dependency_scanning:
  allow_failure: false

secret_detection:
  allow_failure: false
